# MileStone 1
# Renuka Mulay

Import a Csv File and prints first N Rows's First and Third Column.

In [1]:
import json as json
import numpy as np
import pandas as pd
from IPython.display import display

def PrintTitleAndTotalPagesOfBooks(fileName = ""):
    if fileName == "":
        return
    """Parses few key columns from a csv file and loads the data in Pandas dataFrame"""
    data = []
    with open(fileName, newline='') as jsonDoc:  
        for row in json.load(jsonDoc):
            datarow = []
            isbn = None
            pageCount = None
            title = None
            desc_len = None
            has_word_data = None;
            if "isbn" in row:
                isbn = row["isbn"]
            if "pageCount" in row:
                pageCount = row["pageCount"]
            if "title" in row:
                title = row["title"]
            if "longDescription" in row:
                desc_len = len(row["longDescription"].split(" "))
                has_word_data = row["longDescription"].find("data") != -1
            
            datarow.append(len(row["authors"]))
            datarow.append(isbn)
            datarow.append(pageCount)
            datarow.append(title)
            datarow.append(desc_len)
            datarow.append(has_word_data)
            data.append(datarow)
    df = pd.DataFrame(np.array(data), 
                      columns=['Authors_Length', 'ISBN', 'PageCount', 'Title', 'Desc_Length', 'Has_Data'])
    display(df.head(20))

            
PrintTitleAndTotalPagesOfBooks('data/books.json')

,Authors_Length,ISBN,PageCount,Title,Desc_Length,Has_Data
0,3,1933988673,416,Unlocking Android,359,True
1,2,1935182722,592,"Android in Action, Second Edition",107,False
2,1,1617290084,0,Specification by Example,None,None
3,2,1933988746,576,Flex 3 in Action,277,True
4,4,1935182420,600,Flex 4 in Action,351,True
5,1,1933988312,425,Collective Intelligence in Action,261,True
6,3,1933988320,432,Zend Framework in Action,301,True
7,2,1933988797,265,Flex on Java,300,True
8,4,1935182234,375,Griffon in Action,246,False
9,1,193518217X,325,OSGi in Depth,281,False
10,1,1933988509,592,Flexible Rails,392,True
11,1,1933988762,258,Hello! Flex 4,190,True
12,2,1884777384,316,Coffeehouse,101,False
13,1,1933988592,344,Team Foundation Server 2008 in Action,306,True
14,2,1933988711,550,Brownfield Application Development in .NET,279,False
15,1,1935182870,0,MongoDB in Action,339,True
16,1,1884777686,504,Distributed Application Development with Power...,233,False
17,1,1884777864,550,Jaguar Development with PowerBuilder 7,155,False
18,2,1884777686,362,Taming Jaguar,200,True
19,1,1884777902,520,3D User Interfaces with Java 3D,196,True